name: parking_eye
channels:
  - conda-forge
  - pytorch
  - defaults
  - nvidia
dependencies:
  - python=3.9.10
  - cudatoolkit=11.3.1
  - pytorch::pytorch=1.11.0
  - pytorch::torchvision=0.12.0
  - pip=22.0.4
  - pip:
      - opencv-python==4.5.5.64
      - sahi==0.9.0
      - yolov5==6.0.6
      - fastapi==0.75.0
      - uvicorn==0.17.6
      - pyTelegramBotAPI==4.4.0
      - pymongo==4.0.2
      - filterpy==1.4.5
      - scikit-image==0.17.2
      - lap==0.4.0
      - pytest==7.1.1

